[tasks]
openhands = """
docker run -it --rm \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.openhands:/.openhands \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.48
"""

openwebui = """
docker run -d --network=host -p 51433:8080 -e 'OLLAMA_BASE_URL=http://10.1.201.32:3000/v1' -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
"""

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]

[tools]
bun = "1.3.13"
node = "25.9.0"
"npm:@google/gemini-cli" = "0.39.0"
"npm:@openai/codex" = "0.123.0"
python = "3.14.4"
uv = "0.11.7"
go = "1.26.2"
deno = "2.7.13"
java = "26.0.1"
"npm:ccusage" = "18.0.11"
"npm:agent-browser" = "0.26.0"
"npm:@antfu/ni" = "30.1.0"
"npm:typescript" = "6.0.3"
